<?php

namespace ContainerK5gAxVG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GG7bN3FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GG7bN3F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GG7bN3F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\UserController::list' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::list()', 'getUserControllerlistService', true],
            'App\\Controller\\UserController::detail' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::detail()', 'getUserControllerdetailService', true],
            'App\\Controller\\UserController::create' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UserController::create()', 'getUserControllercreateService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.OA38qqg.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.OA38qqg.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\UserController:list' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::list()', 'getUserControllerlistService', true],
            'App\\Controller\\UserController:detail' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::detail()', 'getUserControllerdetailService', true],
            'App\\Controller\\UserController:create' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UserController::create()', 'getUserControllercreateService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.OA38qqg.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.OA38qqg.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\UserController::list' => '?',
            'App\\Controller\\UserController::detail' => '?',
            'App\\Controller\\UserController::create' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\UserController:list' => '?',
            'App\\Controller\\UserController:detail' => '?',
            'App\\Controller\\UserController:create' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:delete' => '?',
        ]);
    }
}
