<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN1Eb2oO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN1Eb2oO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN1Eb2oO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN1Eb2oO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN1Eb2oO\App_KernelDevDebugContainer([
    'container.build_hash' => 'N1Eb2oO',
    'container.build_id' => 'c8e4ed64',
    'container.build_time' => 1751756891,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN1Eb2oO');
