<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXZbtjOo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXZbtjOo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXZbtjOo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXZbtjOo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXZbtjOo\App_KernelDevDebugContainer([
    'container.build_hash' => 'XZbtjOo',
    'container.build_id' => 'b5ec0cb1',
    'container.build_time' => 1754962890,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXZbtjOo');
