<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFmTtiu2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFmTtiu2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFmTtiu2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFmTtiu2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFmTtiu2\App_KernelDevDebugContainer([
    'container.build_hash' => 'FmTtiu2',
    'container.build_id' => '4e9aeea5',
    'container.build_time' => 1750545520,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFmTtiu2');
